# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ba17666895bf0071a4fc5be51614c637"
application_url = "https://mitsubishi--sv-trek.trycloudflare.com"
embedded = true
name = "vowelWeb"
handle = "vowelweb-3"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mitsubishi--sv-trek.trycloudflare.com/auth/callback",
  "https://mitsubishi--sv-trek.trycloudflare.com/auth/shopify/callback",
  "https://mitsubishi--sv-trek.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "vowelweb1.myshopify.com"
automatically_update_urls_on_dev = true
